channels:
  - defaults
dependencies:
  - astropy>=5.1
  - pandas>=1.5.0
  - numpy>=1.24.0
  - pip>=23.1.0
  - python=3.10.0
  - tqdm>=4.65.0
  - dill>=0.3.6
  - jinja2>=3.1.2
  - pip:
      - matplotlib>=3.7.0
      - vice>=1.3.0
      - scipy>=1.10.0
