channels:
  - defaults
dependencies:
  - astropy>=5.0.4
  - pandas>=1.4.2
  - numpy>=1.20
  - pip>=20.3.3
  - python=3.9
  - pip:
      - matplotlib>=3.3.3
      - vice>=1.3.0
      - tqdm>=4.64.0
